export const sliderItems = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Z2lybCUyMGRyZXNzfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    tag: "summer",
  },
  {
    id: 2,
    img: "https://data.whicdn.com/images/301243589/original.jpg?t=1510432849",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 40% OFF FOR NEW ARRIVALS",
    tag: "winter",
  },
  {
    id: 3,
    img: "https://image.freepik.com/free-vector/black-friday-banner-super-sale-discount-fashion-sale-girl_107355-824.jpg",
    title: "SUPER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 60% OFF FOR NEW ARRIVALS",
    tag: "super",
  },
];

export const brandsItems = [
  {
    id: 1,
    img: "https://miro.medium.com/max/1080/1*3K7Du_Ykt3lEZ9rciVQBVw.jpeg",
    brand: "ZARA",
  },
  {
    id: 2,
    img: "https://i.insider.com/5c9d09b97563b02864787b35?width=1000&format=jpeg&auto=webp",
    brand: "LEVIS",
  },
  {
    id: 3,
    img: "https://g3fashion.cdn.imgeng.in/upload/products/global_desi_stuning_peach_georgette_casual_occasions_solid_kurti_1630748427fw21gb061turl_1.jpg",
    brand: "GLOBAL DESI",
  },
];
export const productsItems = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    title: "Random title",
    desc: "Random desc",
    price: 25.99,
    colors: ["blue"],
    size: ["M", "XL"],
    brand: "ZARA",
    clicks: 4,
    sale: "summer",
  },
  {
    id: 2,
    img: "https://img.abercrombie.com/is/image/anf/KIC_155-1252-2632-280_prod1?policy=product-medium&wid=350&hei=438",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "blue"],
    size: ["M", "L"],
    brand: "ZARA",
    clicks: 10,
    sale: "super",
  },
  {
    id: 3,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    title: "Random title",
    desc: "Random desc",
    price: 13.99,
    colors: ["red", "blue"],
    size: ["M", "L"],
    brand: "ZARA",
    clicks: 10,
    sale: "super",
  },
  {
    id: 4,
    img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "LEVIS",
    clicks: 10,
    sale: "",
  },
  {
    id: 5,
    img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "LEVIS",
    clicks: 10,
    sale: "summer",
  },
  {
    id: 6,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "LEVIS",
    clicks: 10,
    sale: "",
  },
  {
    id: 7,
    img: "https://www.helikon-tex.com/media/catalog/product/cache/4/image/500x/17f82f742ffe127f42dca9de82fb58b1/b/l/bl-caf-fl-02.jpeg",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "LEVIS",
    clicks: 4,
    sale: "super",
  },
  {
    id: 8,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "GLOBAL DESI",
    clicks: 4,
    sale: "",
  },
  {
    id: 9,
    img: "https://www.wigglestatic.com/product-media/101782785/Sportful-Women-s-Hot-Pack-Easy-Light-Jacket-Jackets-WHITE-SS19-1102028-101-XXL.jpg",
    title: "Random title",
    desc: "Random desc",
    price: 62.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "GLOBAL DESI",
    clicks: 6,
    sale: "winter",
  },
  {
    id: 10,
    img: "https://media.istockphoto.com/photos/red-elegant-skirt-with-ribbon-bow-isolated-on-white-picture-id882157056?k=20&m=882157056&s=612x612&w=0&h=7FTTXCyF6z0ziAKhjKS1uptuxl5ym9RcGmMD0IZoumo=",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "GLOBAL DESI",
    clicks: 11,
    sale: "winter",
  },
  {
    id: 11,
    img: "https://lt2.pigugroup.eu/colours/352/842/76/35284276/tampres-moterims-kappa-hanne-women-leggings-308006_xbig.jpg",
    title: "Random title",
    desc: "Random desc",
    price: 35.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "ZARA",
    clicks: 6,
    sale: "winter",
  },
  {
    id: 12,
    img: "https://www.stickx.de/static/images/product_images/960x1000x95/2016/CC/02/8004/%28PS%29_%2802.8004%29_-_James_%26_Nicholson_JN_8004_%5Bred%5D_%28Front%29_%281%29.jpg",
    title: "Random title",
    desc: "Random desc",
    price: 69.99,
    colors: ["green", "red", "blue"],
    size: ["M", "L", "XL"],
    brand: "LEVIS",
    clicks: 14,
    sale: "winter",
  },
];
